### ISSUE TITLE
Ontwerpen printplaat

### ISSUE THREAD

**Issue by Tinus899** [daanbreur/the-challenge-hbo-ict#23]

**Comment by daanbreur** [comment]
![PCB_PCB_The Challenge HBO-ICT_2024-01-12-1](https://github.com/daanbreur/the-challenge-hbo-ict/assets/32175349/6a87bb68-0b5c-4c90-865b-781e79de25d3)
![PCB_PCB_The Challenge HBO-ICT_2024-01-12-2](https://github.com/daanbreur/the-challenge-hbo-ict/assets/32175349/92e8f83f-0cb9-4bfe-9d9b-c8a1a2ffaf1a)

**Comment by daanbreur** [comment]
![SCH_The Challenge HBO-ICT_1-Sheet_1_2024-01-12](https://github.com/daanbreur/the-challenge-hbo-ict/assets/32175349/10e90be3-a75b-43e8-9e02-e804da3bd8f0)
![SCH_The Challenge HBO-ICT_2-LEDS_2024-01-12](https://github.com/daanbreur/the-challenge-hbo-ict/assets/32175349/64f50600-d1e8-4e6a-9ddf-8916c2a88161)
![SCH_The Challenge HBO-ICT_3-Battery_2024-01-12](https://github.com/daanbreur/the-challenge-hbo-ict/assets/32175349/f5b0481d-6a5f-4037-85ec-f6166bcd3858)

**Comment by daanbreur** [comment]
Printplaat ontwerp van versie2 van de clicker.
