### ISSUE TITLE
Ontwerpen logo

### ISSUE THREAD

**Issue by Tinus899** [daanbreur/the-challenge-hbo-ict#25]

**Comment by daanbreur** [comment]
@ManuKapel Nieuwe logos voor de app + bedrijf ontworpen (volledige files in de drive)

![CC-NoBack](https://github.com/daanbreur/the-challenge-hbo-ict/assets/32175349/9b90ae9e-5d16-4f4f-847d-ea27305e2f6e)
![ClassClick-Clear (1)](https://github.com/daanbreur/the-challenge-hbo-ict/assets/32175349/fbe6a09a-3d4c-4ab3-ab03-355a97bf52d4)
![CCompanion-1x](https://github.com/daanbreur/the-challenge-hbo-ict/assets/32175349/8208f234-c1ce-4508-92a9-cda59c5385d4)
